# Generated by Django 4.0.5 on 2022-06-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('otp', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
