# Generated by Django 4.0 on 2022-07-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='par',
            new_name='parent',
        ),
    ]
