# Generated by Django 4.0 on 2022-07-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0008_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
